version: '3'

services:
  whoami:
    image: traefik/whoami
    ports:
      - "80:80"
    restart: unless-stopped

  # portainer: 
  #   container_name: portainer
  #   image: portainer/portainer-ce
  #   hostname: portainer
  #   restart: always
  #   # networks: 
  #   #   internal:
  #   #     ipv4_address: 172.18.0.3
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.portainer.rule=Host(`portainer.robotmk.org`)"
  #     - "traefik.http.routers.portainer.entrypoints=websecure"
  #     - "traefik.http.services.portainer.loadbalancer.server.port=9000"
  #     - "traefik.http.routers.portainer.service=portainer"
  #     - "traefik.http.routers.portainer.tls.certresolver=myresolver"    
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #     - "./portainer_data:/data"
#WORKS
  # oxid6_apache:
  #   build: container/apache/.
  #   hostname: ${DOMAIN}
  #   restart: always
  #   depends_on:
  #     - oxid6_mysql
  #   volumes:
  #     - ./data/www/:/var/www/html/:cached
  #   environment:
  #     DOMAIN: ${DOMAIN}
  #     APACHE_PORT: ${APACHE_PORT}
  #     OXID_VERSION: ${OXID_VERSION}
  #     OXID_DEMODATA: ${OXID_DEMODATA}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   ports:
  #     - ${APACHE_PORT}:80
  #     - ${APACHE_HTTPS_PORT}:443
  #   links:
  #     - oxid6_mailhog:mail.server
      
  # oxid6_mysql:
  #   # platform: 'linux/x86_64'
  #   image: mysql:5.7
  #   hostname: mysql.${DOMAIN}
  #   restart: always
  #   volumes:
  #     - ./data/mysql/:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  # oxid6_mailhog:
  #   hostname: mailhog.${DOMAIN}
  #   image: mailhog/mailhog:latest
  #   ports:
  #     - ${MAILHOG_PORT}:8025

  # oxid6_phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   ports:
  #     - ${PHPMYADMIN_PORT}:80
  #   environment:
  #     PMA_HOST: oxid6_mysql
#/WORKS


# volumes:
#   postgres_data_volume:
#   portainer_data: